package AdditionApp;


/**
* AdditionApp/AdditionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* wtorek, 21 stycznia 2020 22:50:23 CET
*/

public interface AdditionOperations 
{
  float[] b_sort (String tab);
  void shutdown ();
} // interface AdditionOperations
