package AdditionApp;


/**
* AdditionApp/floatSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* wtorek, 21 stycznia 2020 22:50:23 CET
*/

public final class floatSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public float value[] = null;

  public floatSeqHolder ()
  {
  }

  public floatSeqHolder (float[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdditionApp.floatSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdditionApp.floatSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdditionApp.floatSeqHelper.type ();
  }

}
